/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function DogModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/model/dog.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="dog" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="GLTF_created_0">
                <skinnedMesh
                  name="Object_68"
                  geometry={nodes.Object_68.geometry}
                  material={materials.material_0}
                  skeleton={nodes.Object_68.skeleton}
                />
                <group name="Rover_1_correction">
                  <group name="Rover_1" />
                </group>
                <group name="Rover_footprint_4_correction">
                  <group name="Rover_footprint_4" />
                </group>
                <group name="Rover_travel_bag_3_correction">
                  <group name="Rover_travel_bag_3" />
                </group>
                <primitive object={nodes.GLTF_created_0_rootJoint} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model/dog.glb");
